
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        ## Api Routes
        - id: auth-api
          uri: lb://authservice
          predicates:
            - Path=/auth/**

        - id: user-api
          uri: lb://userservice
          predicates:
            - Path=/user/**

        - id: master-api
          uri: lb://masterservice
          predicates:
            - Path=/master/**

        ## Swagger Routes
        - id: auth-swagger
          uri: lb://authservice
          predicates:
            - Path=/swagger/auth
          filters:
            - RewritePath=/swagger/?(?<segment>.*), /$\{segment}/public/api-docs

        - id: user-swagger
          uri: lb://userservice
          predicates:
            - Path=/swagger/user
          filters:
            - RewritePath=/swagger/?(?<segment>.*), /$\{segment}/public/api-docs

        - id: master-swagger
          uri: lb://masterservice
          predicates:
            - Path=/swagger/master
          filters:
            - RewritePath=/swagger/?(?<segment>.*), /$\{segment}/public/api-docs

  config:
    import: 'optional:configserver:'

server:
  port: 8080

eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
app:
  whitelistedPaths:
    - /*/public/**

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /swagger/auth
      - name: User Service
        url: /swagger/user
      - name: Master Service
        url: /swagger/master

