spring:
  application:
    name: configservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workspark
    username: root
    password: root
  cloud:
    config:
      server:
        prefix: /properties
        jdbc:
          sql: "select property_key, property_value from config_properties where application_name = ? and profile = ? and label = ?"
          order: 1
  profiles:
    active: jdbc
  jpa:
    show-sql: true

server:
  port: 8081
  servlet:
    context-path: /config

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health

eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
    hostname: localhost
    metadataMap:
      configPath: /config/properties
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /public/api-docs   # Path for the Swagger API docs